"""final

Revision ID: 29bf6e89028a
Revises: 6570c69256c2
Create Date: 2025-11-04 15:31:45.818505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29bf6e89028a'
down_revision: Union[str, Sequence[str], None] = '6570c69256c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likedcomments', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('unique_likecomment'), 'likedcomments', type_='unique')
    op.create_unique_constraint('unique_likecomment', 'likedcomments', ['user_id', 'comment_id'])
    op.drop_constraint(op.f('likedcomments_comment_fkey'), 'likedcomments', type_='foreignkey')
    op.create_foreign_key(None, 'likedcomments', 'comments', ['comment_id'], ['id'], ondelete='CASCADE')
    op.drop_column('likedcomments', 'comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likedcomments', sa.Column('comment', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'likedcomments', type_='foreignkey')
    op.create_foreign_key(op.f('likedcomments_comment_fkey'), 'likedcomments', 'comments', ['comment'], ['id'], ondelete='CASCADE')
    op.drop_constraint('unique_likecomment', 'likedcomments', type_='unique')
    op.create_unique_constraint(op.f('unique_likecomment'), 'likedcomments', ['user_id', 'comment'], postgresql_nulls_not_distinct=False)
    op.drop_column('likedcomments', 'comment_id')
    # ### end Alembic commands ###
