"""user_image

Revision ID: e40e11ef185e
Revises: 0f78917a6af3
Create Date: 2025-11-08 18:05:56.494747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e40e11ef185e'
down_revision: Union[str, Sequence[str], None] = '0f78917a6af3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['image_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'image_url')
    # ### end Alembic commands ###
